// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RiskHuntingAppTest {
	
	
	public partial class ActionPlan {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl TopbarProblemSolution;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl TopbarProblemSearchSolution;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl topbar_v2;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl SubmitReport;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl content2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl sourceDiv;
		
		protected System.Web.UI.WebControls.DropDownList ActionDropDown;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl EditSection;
		
		protected World.Code.WebControls.WatermarkedTextBox EditActionDescription;
		
		protected World.Code.WebControls.WatermarkedTextBox EditActionOwner;
		
		protected System.Web.UI.HtmlControls.HtmlSelect EditImplementedDay;
		
		protected System.Web.UI.HtmlControls.HtmlSelect EditImplementedMonth;
		
		protected System.Web.UI.HtmlControls.HtmlSelect EditImplementedYear;
		
		protected System.Web.UI.WebControls.Button UpdateAction;
		
		protected System.Web.UI.WebControls.Button DeleteAction;
		
		protected World.Code.WebControls.WatermarkedTextBox AddActionDescription;
		
		protected World.Code.WebControls.WatermarkedTextBox AddActionOwner;
		
		protected System.Web.UI.HtmlControls.HtmlSelect AddImplementedDay;
		
		protected System.Web.UI.HtmlControls.HtmlSelect AddImplementedMonth;
		
		protected System.Web.UI.HtmlControls.HtmlSelect AddImplementedYear;
		
		protected System.Web.UI.WebControls.Button AddAction;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl saveRisk;
		
		protected System.Web.UI.WebControls.Button saveRiskButton;
	}
}
