// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RiskHuntingAppTest {
	
	
	public partial class AddAction {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl TopbarProblemIdeas;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected World.Code.WebControls.WatermarkedTextBox AddActionDescription;
		
		protected World.Code.WebControls.WatermarkedTextBox AddActionOwner;
		
		protected System.Web.UI.HtmlControls.HtmlSelect AddImplementedDay;
		
		protected System.Web.UI.HtmlControls.HtmlSelect AddImplementedMonth;
		
		protected System.Web.UI.HtmlControls.HtmlSelect AddImplementedYear;
		
		protected System.Web.UI.WebControls.Button AddNewAction;
	}
}
