// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RiskHuntingAppTest {
	
	
	public partial class CreateSource {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl SubmitReport;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl DomainErrorMsg;
		
		protected System.Web.UI.WebControls.DropDownList DomainDropDown;
		
		protected World.Code.WebControls.WatermarkedTextBox SourceTextBox;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl NameErrorMsg;
		
		protected World.Code.WebControls.WatermarkedTextBox NameTextBox;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl ProblemDescrErrorMsg;
		
		protected World.Code.WebControls.WatermarkedTextBox ProblemDescrTextBox;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl SolutionDescrErrorMsg;
		
		protected World.Code.WebControls.WatermarkedTextBox SolutionDescrTextBox;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl MiscellaneousErrorMsg;
		
		protected World.Code.WebControls.WatermarkedTextBox MiscellaneousTextBox;
		
		protected System.Web.UI.WebControls.DropDownList ObservedBehaviourDropDown;
		
		protected System.Web.UI.WebControls.Button submit;
		
		protected System.Web.UI.WebControls.Button reset;
	}
}
