// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RiskHuntingAppTest {
	
	
	public partial class CreateRisk {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl title;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl navigationbar;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl errorMsg;
		
		protected System.Web.UI.WebControls.TextBox RiskName;
		
		protected System.Web.UI.WebControls.TextBox RiskDanger;
		
		protected System.Web.UI.WebControls.TextBox RiskLocation;
		
		protected System.Web.UI.WebControls.TextBox RiskRisk;
		
		protected System.Web.UI.WebControls.TextBox RiskDescription;
		
		protected System.Web.UI.WebControls.TextBox RiskBodyParts;
		
		protected System.Web.UI.WebControls.Button submit;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl previousrisks;
		
		protected System.Web.UI.WebControls.Button previousrisksButton;
	}
}
