// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RiskHuntingAppTest {
	
	
	public partial class CreateIdeas_PastRisk {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl alert_message_success;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl successMessage;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl alert_message_error;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl errorMessage;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl hint_box;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl creativeGuidance;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl content2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl generatePrompts;
		
		protected System.Web.UI.WebControls.Button GenerateAgain;
	}
}
