// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RiskHuntingAppTest {


	public partial class Default {

		protected System.Web.UI.HtmlControls.HtmlGenericControl TopbarProblemSolution;

		protected System.Web.UI.HtmlControls.HtmlGenericControl TopbarProblemSearchSolution;

		protected System.Web.UI.HtmlControls.HtmlGenericControl navigationbar;

		protected System.Web.UI.HtmlControls.HtmlForm form1;

		protected System.Web.UI.ScriptManager ScriptManager1;

		protected System.Web.UI.Timer Timer1;

		protected System.Web.UI.UpdatePanel UpdatePanel1;

		protected System.Web.UI.WebControls.Label AutoSaveLabel;

		protected System.Web.UI.HtmlControls.HtmlGenericControl errorMsg;

		protected World.Code.WebControls.WatermarkedTextBox RiskName;

		protected World.Code.WebControls.WatermarkedTextBox RiskDescription;

		protected World.Code.WebControls.WatermarkedTextBox RiskAuthor;

		protected System.Web.UI.HtmlControls.HtmlSelect RiskLocation;

		protected System.Web.UI.HtmlControls.HtmlSelect RiskBodyParts;  

		protected System.Web.UI.WebControls.Button submit;

		protected System.Web.UI.HtmlControls.HtmlGenericControl previousrisks;

		protected System.Web.UI.WebControls.Button previousrisksButton;

		protected System.Web.UI.HtmlControls.HtmlGenericControl creativeGuidance;
	}
}