// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RiskHuntingAppTest {
	
	
	public partial class DisplayResponse_CreativeGuidance {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl TopbarProblemSearchSolution;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl topbar_v2;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl creativeGuidance;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl SubmitReport;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl RiskName;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl generatePrompts;
		
		protected System.Web.UI.WebControls.Button GenerateAgain;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl content2;
		
		protected System.Web.UI.WebControls.Button MorePrompts;
		
		protected System.Web.UI.WebControls.Button SaveSelected;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl ResolutionIdeas;
		
		protected System.Web.UI.WebControls.Button resolutionIdeasButton;
	}
}
