// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RiskHuntingAppTest {
	
	
	public partial class DisplayResponse_Description {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl TopbarProblemSearchSolution;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl topbar_v2;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label RiskName;
		
		protected System.Web.UI.WebControls.Label RiskDescription;
		
		protected System.Web.UI.WebControls.Label RiskDanger;
		
		protected System.Web.UI.WebControls.Label RiskLocation;
		
		protected System.Web.UI.WebControls.Label RiskBodyParts;
		
		protected System.Web.UI.WebControls.Button MoveOn;
	}
}
