// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RiskHuntingAppTest {
	
	
	public partial class EditAction {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl TopbarProblemIdeas;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected World.Code.WebControls.WatermarkedTextBox EditActionDescription;
		
		protected World.Code.WebControls.WatermarkedTextBox EditActionOwner;
		
		protected System.Web.UI.HtmlControls.HtmlSelect EditImplementedDay;
		
		protected System.Web.UI.HtmlControls.HtmlSelect EditImplementedMonth;
		
		protected System.Web.UI.HtmlControls.HtmlSelect EditImplementedYear;
		
		protected System.Web.UI.WebControls.Button UpdateAction;
		
		protected System.Web.UI.WebControls.Button DeleteAction;
	}
}
