// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RiskHuntingAppTest {
	
	
	public partial class Feedback {
		
		protected System.Web.UI.WebControls.Panel Panel1;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator11;
		
		protected System.Web.UI.WebControls.TextBox YourName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
		
		protected System.Web.UI.WebControls.TextBox Comments;
		
		protected System.Web.UI.WebControls.Button btnSubmit;
		
		protected System.Web.UI.WebControls.Label lblMsgSend;
	}
}
