// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RiskHuntingAppTest {
	
	
	public partial class ResolveRisk {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl alert_message_success;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl successMessage;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl alert_message_error;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl errorMessage;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divIdeas;
		
		protected System.Web.UI.WebControls.Label statusLabel;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl AddNewIdeaDiv;
		
		protected System.Web.UI.WebControls.Button AddNewIdea;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl content2;
	}
}
