// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RiskHuntingAppTest {
	
	
	public partial class Solution_ResolutionIdeas {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl TopbarProblemSolution;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl TopbarProblemSearchSolution;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl topbar_v2;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl SubmitReport;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divIdeas;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl AddNewIdeaDiv;
		
		protected System.Web.UI.WebControls.Button AddNewIdea;
		
		protected System.Web.UI.WebControls.Label statusLabel;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl content2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl GoBackDiv;
		
		protected System.Web.UI.WebControls.Button GoBack;
	}
}
