// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RiskHuntingAppTest {
	
	
	public partial class Summary {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl TopbarProblemSearchSolution;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl creativeGuidance;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl sourceDiv;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divActions;
		
		protected System.Web.UI.WebControls.Label statusLabel;
		
		protected System.Web.UI.WebControls.Button Export;
	}
}
