//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections;
using System.Collections.Generic;

namespace XmlProc
{
     
    /// <summary>
    /// 
    /// </summary>
    public class ProblemSerialized
    {
        /// <summary>
        /// 
        /// </summary>
        public ProblemSerialized()
        {
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
        public partial class LanguageSpecificSpecification
        {

            private string facetTypeField;

            private string facetSpecificationLanguageField;

            private string authorField;

            private string launchDateField;

            private string sourceSpecificationLastEditedField;

            private LanguageSpecificSpecificationFacetSpecificationData facetSpecificationDataField;

            /// <remarks/>
            public string FacetType
            {
                get
                {
                    return this.facetTypeField;
                }
                set
                {
                    this.facetTypeField = value;
                }
            }

            /// <remarks/>
            public string FacetSpecificationLanguage
            {
                get
                {
                    return this.facetSpecificationLanguageField;
                }
                set
                {
                    this.facetSpecificationLanguageField = value;
                }
            }

            /// <remarks/>
            public string Author
            {
                get
                {
                    return this.authorField;
                }
                set
                {
                    this.authorField = value;
                }
            }

            /// <remarks/>
            public string LaunchDate
            {
                get
                {
                    return this.launchDateField;
                }
                set
                {
                    this.launchDateField = value;
                }
            }

            /// <remarks/>
            public string SourceSpecificationLastEdited
            {
                get
                {
                    return this.sourceSpecificationLastEditedField;
                }
                set
                {
                    this.sourceSpecificationLastEditedField = value;
                }
            }

            /// <remarks/>
            public LanguageSpecificSpecificationFacetSpecificationData FacetSpecificationData
            {
                get
                {
                    return this.facetSpecificationDataField;
                }
                set
                {
                    this.facetSpecificationDataField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LanguageSpecificSpecificationFacetSpecificationData
        {

            private string contentField;

            private List<string> observationsField = new List<string>();
            //private string observationsField;

			private string injuryNatureField;

			private string locationDetailField;

			private string bodyPartField;

			private string injuryCauseField;

			private string incidentPriorityField;

			private string incidentStatusField;

			private string rootCauseField;

			private string routineWorkField;

			private string shiftTypeField;

			private string titleField;

			private string closedByOperatorField;

			private string contractorNameField;

			private string dateClosedField;

			private string dateIncidentOccurredField;

			private string miscellaneousField;

            private string matchingDetailsField;

            /// <remarks/>
            public string Content
            {
                get
                {
                    return this.contentField;
                }
                set
                {
                    this.contentField = value;
                }
            }

            /// <remarks/>
			public string InjuryNature
            {
                get
                {
					return this.injuryNatureField;
                }
                set
                {
					this.injuryNatureField = value;
                }
            }

            /// <remarks/>
			public string LocationDetail
            {
                get
                {
					return this.locationDetailField;
                }
                set
                {
					this.locationDetailField = value;
                }
            }

            /// <remarks/>
			public string BodyPart
            {
                get
                {
					return this.bodyPartField;
                }
                set
                {
					this.bodyPartField = value;
                }
            }

            /// <remarks/>
			public string InjuryCause
            {
                get
                {
					return this.injuryCauseField;
                }
                set
                {
					this.injuryCauseField = value;
                }
            }

            /// <remarks/>
			public string IncidentPriority
            {
                get
                {
					return this.incidentPriorityField;
                }
                set
                {
					this.incidentPriorityField = value;
                }
            }

            /// <remarks/>
			public string IncidentStatus
            {
                get
                {
					return this.incidentStatusField;
                }
                set
                {
					this.incidentStatusField = value;
                }
            }

			/// <remarks/>
			public string RootCause
			{
				get
				{
					return this.rootCauseField;
				}
				set
				{
					this.rootCauseField = value;
				}
			}

			/// <remarks/>
			public string RoutineWork
			{
				get
				{
					return this.routineWorkField;
				}
				set
				{
					this.routineWorkField = value;
				}
			}

			/// <remarks/>
			public string ShiftType
			{
				get
				{
					return this.shiftTypeField;
				}
				set
				{
					this.shiftTypeField = value;
				}
			}

			/// <remarks/>
			public string Title
			{
				get
				{
					return this.titleField;
				}
				set
				{
					this.titleField = value;
				}
			}

			/// <remarks/>
			public string ClosedByOperator
			{
				get
				{
					return this.closedByOperatorField;
				}
				set
				{
					this.closedByOperatorField = value;
				}
			}

			/// <remarks/>
			public string ContractorName
			{
				get
				{
					return this.contractorNameField;
				}
				set
				{
					this.contractorNameField = value;
				}
			}

			/// <remarks/>
			public string DateClosed
			{
				get
				{
					return this.dateClosedField;
				}
				set
				{
					this.dateClosedField = value;
				}
			}

			/// <remarks/>
			public string DateIncidentOccurred
			{
				get
				{
					return this.dateIncidentOccurredField;
				}
				set
				{
					this.dateIncidentOccurredField = value;
				}
			}

            /// <remarks/>
            public string Miscellaneous
            {
                get
                {
                    return this.miscellaneousField;
                }
                set
                {
                    this.miscellaneousField = value;
                }
            }

            /// <remarks/>
            public string MatchingDetails
            {
                get
                {
                    return this.matchingDetailsField;
                }
                set
                {
                    this.matchingDetailsField = value;
                }
            }
        }
			
    }
}