//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Collections;
using System.Collections.Generic;

namespace XmlProc
{

    /// <summary>
    /// 
    /// </summary>
    public class RequestSerialized
    {
        /// <summary>
        /// 
        /// </summary>
        public RequestSerialized()
        {
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://achernar.soi.city.ac.uk/xmlSchemas/Request")]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://achernar.soi.city.ac.uk/xmlSchemas/Request", IsNullable = false)]
        public partial class Request
        {

            private List<RegistryComponent> registriesField;

            private RequestProperties propertiesField;

            private string dateTimeField;

            private SimilarityType similarityTypeField;

            private List<RequestDataSource> dataSourceField = new List<RequestDataSource>();

            private List<RequestTarget> targetField = new List<RequestTarget>();

            private string requestIdField;

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("Registry", IsNullable = false)]
            public List<RegistryComponent> Registries
            {
                get
                {
                    return this.registriesField;
                }
                set
                {
                    this.registriesField = value;
                }
            }

            /// <remarks/>
            public RequestProperties Properties
            {
                get
                {
                    return this.propertiesField;
                }
                set
                {
                    this.propertiesField = value;
                }
            }

            /// <remarks/>
            public string DateTime
            {
                get
                {
                    return this.dateTimeField;
                }
                set
                {
                    this.dateTimeField = value;
                }
            }

            /// <remarks/>
            public SimilarityType SimilarityType
            {
                get
                {
                    return this.similarityTypeField;
                }
                set
                {
                    this.similarityTypeField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("DataSource")]
            public List<RequestDataSource> DataSource
            {
                get
                {
                    return this.dataSourceField;
                }
                set
                {
                    this.dataSourceField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Target")]
            public List<RequestTarget> Target
            {
                get
                {
                    return this.targetField;
                }
                set
                {
                    this.targetField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
            public string requestId
            {
                get
                {
                    return this.requestIdField;
                }
                set
                {
                    this.requestIdField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://achernar.soi.city.ac.uk/xmlSchemas/Request")]
        public partial class RegistryComponent
        {

            private List<RegistryComponentProperty> propertyField;

            private string typeField;

            private string nameField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Property")]
            public List<RegistryComponentProperty> Property
            {
                get
                {
                    return this.propertyField;
                }
                set
                {
                    this.propertyField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string type
            {
                get
                {
                    return this.typeField;
                }
                set
                {
                    this.typeField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name
            {
                get
                {
                    return this.nameField;
                }
                set
                {
                    this.nameField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://achernar.soi.city.ac.uk/xmlSchemas/Request")]
        public partial class RegistryComponentProperty
        {

            private string nameField;

            private string valueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name
            {
                get
                {
                    return this.nameField;
                }
                set
                {
                    this.nameField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string value
            {
                get
                {
                    return this.valueField;
                }
                set
                {
                    this.valueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://achernar.soi.city.ac.uk/xmlSchemas/Request")]
        public partial class TermExpansionComponent
        {

            private string synonymField;

            private string hypernymField;

            private string glossField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
            public string synonym
            {
                get
                {
                    return this.synonymField;
                }
                set
                {
                    this.synonymField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
            public string hypernym
            {
                get
                {
                    return this.hypernymField;
                }
                set
                {
                    this.hypernymField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
            public string gloss
            {
                get
                {
                    return this.glossField;
                }
                set
                {
                    this.glossField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://achernar.soi.city.ac.uk/xmlSchemas/Request")]
        public partial class PartOfSpeechComponent
        {

            private string adjectiveField;

            private string adverbField;

            private string verbField;

            private string nounField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
            public string adjective
            {
                get
                {
                    return this.adjectiveField;
                }
                set
                {
                    this.adjectiveField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
            public string adverb
            {
                get
                {
                    return this.adverbField;
                }
                set
                {
                    this.adverbField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
            public string verb
            {
                get
                {
                    return this.verbField;
                }
                set
                {
                    this.verbField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(DataType = "integer")]
            public string noun
            {
                get
                {
                    return this.nounField;
                }
                set
                {
                    this.nounField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://achernar.soi.city.ac.uk/xmlSchemas/Request")]
        public partial class RequestProperties
        {

            private PartOfSpeechComponent partOfSpeechField;

            private TermExpansionComponent termExpansionField;

            private string maxResultsField;

            /// <remarks/>
            public PartOfSpeechComponent PartOfSpeech
            {
                get
                {
                    return this.partOfSpeechField;
                }
                set
                {
                    this.partOfSpeechField = value;
                }
            }

            /// <remarks/>
            public TermExpansionComponent TermExpansion
            {
                get
                {
                    return this.termExpansionField;
                }
                set
                {
                    this.termExpansionField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
            public string MaxResults
            {
                get
                {
                    return this.maxResultsField;
                }
                set
                {
                    this.maxResultsField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
        [System.SerializableAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://achernar.soi.city.ac.uk/xmlSchemas/Request")]
        public enum SimilarityType
        {

            /// <remarks/>
            Analogy,

            /// <remarks/>
            LiteralSimilarity,

            /// <remarks/>
            MereAppearance,

            /// <remarks/>
            Eddie,
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://achernar.soi.city.ac.uk/xmlSchemas/Request")]
        public partial class RequestDataSource
        {

            private DataSourceType typeField;

            private string uriField;

            /// <remarks/>
            public DataSourceType Type
            {
                get
                {
                    return this.typeField;
                }
                set
                {
                    this.typeField = value;
                }
            }

            /// <remarks/>
            public string Uri
            {
                get
                {
                    return this.uriField;
                }
                set
                {
                    this.uriField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
        [System.SerializableAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://achernar.soi.city.ac.uk/xmlSchemas/Request")]
        public enum DataSourceType
        {

            /// <remarks/>
            Service,

            /// <remarks/>
            Web,

            /// <remarks/>
            P2P,

            /// <remarks/>
            Document,
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://achernar.soi.city.ac.uk/xmlSchemas/Request")]
        public partial class RequestTarget
        {

            private string targetDescriptionField;

            private string observedBehaviourField;

            private string treatmentTypeField;

            private string dateOfIncidentField;

            private string ailmentTypeField;

            private string triggeringEventField;

            /// <remarks/>
            public string TargetDescription
            {
                get
                {
                    return this.targetDescriptionField;
                }
                set
                {
                    this.targetDescriptionField = value;
                }
            }

            /// <remarks/>
            public string ObservedBehaviour
            {
                get
                {
                    return this.observedBehaviourField;
                }
                set
                {
                    this.observedBehaviourField = value;
                }
            }

            /// <remarks/>
            public string TreatmentType
            {
                get
                {
                    return this.treatmentTypeField;
                }
                set
                {
                    this.treatmentTypeField = value;
                }
            }

            /// <remarks/>
            public string DateOfIncident
            {
                get
                {
                    return this.dateOfIncidentField;
                }
                set
                {
                    this.dateOfIncidentField = value;
                }
            }

            /// <remarks/>
            public string AilmentType
            {
                get
                {
                    return this.ailmentTypeField;
                }
                set
                {
                    this.ailmentTypeField = value;
                }
            }

            /// <remarks/>
            public string TriggeringEvent
            {
                get
                {
                    return this.triggeringEventField;
                }
                set
                {
                    this.triggeringEventField = value;
                }
            }
        }

    }
}