//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

using System.Xml.Serialization;
using System.Collections;
using System.Collections.Generic;

namespace XmlProc {
    

    /// <summary>
    /// 
    /// </summary>
    public class SolutionAdvancedSerialized
    {
        /// <summary>
        /// 
        /// </summary>
        public SolutionAdvancedSerialized()
        {
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
        public partial class LanguageSpecificSpecification
        {

            private string facetTypeField;

            private string facetSpecificationLanguageField;

            private string authorField;

            private string launchDateField;

            private string sourceSpecificationLastEditedField;

            private LanguageSpecificSpecificationFacetSpecificationData facetSpecificationDataField;

            /// <remarks/>
            public string FacetType
            {
                get
                {
                    return this.facetTypeField;
                }
                set
                {
                    this.facetTypeField = value;
                }
            }

            /// <remarks/>
            public string FacetSpecificationLanguage
            {
                get
                {
                    return this.facetSpecificationLanguageField;
                }
                set
                {
                    this.facetSpecificationLanguageField = value;
                }
            }

            /// <remarks/>
            public string Author
            {
                get
                {
                    return this.authorField;
                }
                set
                {
                    this.authorField = value;
                }
            }

            /// <remarks/>
            public string LaunchDate
            {
                get
                {
                    return this.launchDateField;
                }
                set
                {
                    this.launchDateField = value;
                }
            }

            /// <remarks/>
            public string SourceSpecificationLastEdited
            {
                get
                {
                    return this.sourceSpecificationLastEditedField;
                }
                set
                {
                    this.sourceSpecificationLastEditedField = value;
                }
            }

            /// <remarks/>
            public LanguageSpecificSpecificationFacetSpecificationData FacetSpecificationData
            {
                get
                {
                    return this.facetSpecificationDataField;
                }
                set
                {
                    this.facetSpecificationDataField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LanguageSpecificSpecificationFacetSpecificationData
        {

            private LanguageSpecificSpecificationFacetSpecificationDataDifferentPerspectives differentPerspectivesField;

            private LanguageSpecificSpecificationFacetSpecificationDataCarePlan carePlanField;

			private List<string> creativityCluesField;

			private List<LanguageSpecificSpecificationFacetSpecificationDataResourceContent> resourcesField;

			private List<LanguageSpecificSpecificationFacetSpecificationDataCommentContent> commentsField;


            private string miscellaneousField;

            /// <remarks/>
            public LanguageSpecificSpecificationFacetSpecificationDataDifferentPerspectives DifferentPerspectives
            {
                get
                {
                    return this.differentPerspectivesField;
                }
                set
                {
                    this.differentPerspectivesField = value;
                }
            }

            /// <remarks/>
            public LanguageSpecificSpecificationFacetSpecificationDataCarePlan CarePlan
            {
                get
                {
                    return this.carePlanField;
                }
                set
                {
                    this.carePlanField = value;
                }
            }

			/// <remarks/>
			[System.Xml.Serialization.XmlArrayItemAttribute("CreativityClue", IsNullable = false)]
			public List<string> CreativityClues
			{
				get
				{
					return this.creativityCluesField;
				}
				set
				{
					this.creativityCluesField = value;
				}
			}


			/// <remarks/>
			[System.Xml.Serialization.XmlArrayItemAttribute("Resource", IsNullable = false)]
			public List<LanguageSpecificSpecificationFacetSpecificationDataResourceContent> Resources
			{
				get
				{
					return this.resourcesField;
				}
				set
				{
					this.resourcesField = value;
				}
			}

			/// <remarks/>
			[System.Xml.Serialization.XmlArrayItemAttribute("Comment", IsNullable = false)]
			public List<LanguageSpecificSpecificationFacetSpecificationDataCommentContent> Comments
			{
				get
				{
					return this.commentsField;
				}
				set
				{
					this.commentsField = value;
				}
			}

            /// <remarks/>
            public string Miscellaneous
            {
                get
                {
                    return this.miscellaneousField;
                }
                set
                {
                    this.miscellaneousField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LanguageSpecificSpecificationFacetSpecificationDataDifferentPerspectives
        {

            private List<LanguageSpecificSpecificationFacetSpecificationDataDifferentPerspectivesCarerContent> carerField;

            private List<LanguageSpecificSpecificationFacetSpecificationDataDifferentPerspectivesFamilyMemberContent> familyMemberField;

            private List<LanguageSpecificSpecificationFacetSpecificationDataDifferentPerspectivesResidentContent> residentField;

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("CarerContent", IsNullable = false)]
            public List<LanguageSpecificSpecificationFacetSpecificationDataDifferentPerspectivesCarerContent> Carer
            {
                get
                {
                    return this.carerField;
                }
                set
                {
                    this.carerField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("FamilyMemberContent", IsNullable = false)]
            public List<LanguageSpecificSpecificationFacetSpecificationDataDifferentPerspectivesFamilyMemberContent> FamilyMember
            {
                get
                {
                    return this.familyMemberField;
                }
                set
                {
                    this.familyMemberField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("ResidentContent", IsNullable = false)]
            public List<LanguageSpecificSpecificationFacetSpecificationDataDifferentPerspectivesResidentContent> Resident
            {
                get
                {
                    return this.residentField;
                }
                set
                {
                    this.residentField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LanguageSpecificSpecificationFacetSpecificationDataDifferentPerspectivesCarerContent
        {

            private string idField;

            private string titleField;

            private string valueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string title
            {
                get
                {
                    return this.titleField;
                }
                set
                {
                    this.titleField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlTextAttribute()]
            public string Value
            {
                get
                {
                    return this.valueField;
                }
                set
                {
                    this.valueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LanguageSpecificSpecificationFacetSpecificationDataDifferentPerspectivesFamilyMemberContent
        {

            private string idField;

            private string titleField;

            private string valueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string title
            {
                get
                {
                    return this.titleField;
                }
                set
                {
                    this.titleField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlTextAttribute()]
            public string Value
            {
                get
                {
                    return this.valueField;
                }
                set
                {
                    this.valueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LanguageSpecificSpecificationFacetSpecificationDataDifferentPerspectivesResidentContent
        {

            private string idField;

            private string titleField;

            private string valueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string title
            {
                get
                {
                    return this.titleField;
                }
                set
                {
                    this.titleField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlTextAttribute()]
            public string Value
            {
                get
                {
                    return this.valueField;
                }
                set
                {
                    this.valueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LanguageSpecificSpecificationFacetSpecificationDataCarePlan
        {

            private List<LanguageSpecificSpecificationFacetSpecificationDataCarePlanRelationshipsContent> relationshipsField;

            private List<LanguageSpecificSpecificationFacetSpecificationDataCarePlanHealthContent> healthField;

            private List<LanguageSpecificSpecificationFacetSpecificationDataCarePlanEnvironmentContent> environmentField;

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("RelationshipsContent", IsNullable = false)]
            public List<LanguageSpecificSpecificationFacetSpecificationDataCarePlanRelationshipsContent> Relationships
            {
                get
                {
                    return this.relationshipsField;
                }
                set
                {
                    this.relationshipsField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("HealthContent", IsNullable = false)]
            public List<LanguageSpecificSpecificationFacetSpecificationDataCarePlanHealthContent> Health
            {
                get
                {
                    return this.healthField;
                }
                set
                {
                    this.healthField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("EnvironmentContent", IsNullable = false)]
            public List<LanguageSpecificSpecificationFacetSpecificationDataCarePlanEnvironmentContent> Environment
            {
                get
                {
                    return this.environmentField;
                }
                set
                {
                    this.environmentField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LanguageSpecificSpecificationFacetSpecificationDataCarePlanRelationshipsContent
        {

            private string idField;

            private string titleField;

            private string valueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string title
            {
                get
                {
                    return this.titleField;
                }
                set
                {
                    this.titleField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlTextAttribute()]
            public string Value
            {
                get
                {
                    return this.valueField;
                }
                set
                {
                    this.valueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LanguageSpecificSpecificationFacetSpecificationDataCarePlanHealthContent
        {

            private string idField;

            private string titleField;

            private string valueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string title
            {
                get
                {
                    return this.titleField;
                }
                set
                {
                    this.titleField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlTextAttribute()]
            public string Value
            {
                get
                {
                    return this.valueField;
                }
                set
                {
                    this.valueField = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class LanguageSpecificSpecificationFacetSpecificationDataCarePlanEnvironmentContent
        {

            private string idField;

            private string titleField;

            private string valueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string id
            {
                get
                {
                    return this.idField;
                }
                set
                {
                    this.idField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string title
            {
                get
                {
                    return this.titleField;
                }
                set
                {
                    this.titleField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlTextAttribute()]
            public string Value
            {
                get
                {
                    return this.valueField;
                }
                set
                {
                    this.valueField = value;
                }
            }
        }

//		/// <remarks/>
//		[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
//		[System.SerializableAttribute()]
//		[System.Diagnostics.DebuggerStepThroughAttribute()]
//		[System.ComponentModel.DesignerCategoryAttribute("code")]
//		[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
//		public partial class LanguageSpecificSpecificationFacetSpecificationDataCreativityClues
//		{
//			private List<string> creativityClueField;
//
//			/// <remarks/>
//			[System.Xml.Serialization.XmlArrayItemAttribute("CreativityClue", IsNullable = false)]
//			public List<string> CreativityClue
//			{
//				get
//				{
//					return this.creativityClueField;
//				}
//				set
//				{
//					this.creativityClueField = value;
//				}
//			}
//
//		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute("code")]
		[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
		public partial class LanguageSpecificSpecificationFacetSpecificationDataResourceContent
		{

			private string idField;

			private string urlField;

			private string valueField;

			/// <remarks/>
			[System.Xml.Serialization.XmlAttributeAttribute()]
			public string id
			{
				get
				{
					return this.idField;
				}
				set
				{
					this.idField = value;
				}
			}

			/// <remarks/>
			[System.Xml.Serialization.XmlAttributeAttribute()]
			public string url
			{
				get
				{
					return this.urlField;
				}
				set
				{
					this.urlField = value;
				}
			}

			/// <remarks/>
			[System.Xml.Serialization.XmlTextAttribute()]
			public string Value
			{
				get
				{
					return this.valueField;
				}
				set
				{
					this.valueField = value;
				}
			}
		}

		/// <remarks/>
		[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
		[System.SerializableAttribute()]
		[System.Diagnostics.DebuggerStepThroughAttribute()]
		[System.ComponentModel.DesignerCategoryAttribute("code")]
		[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
		public partial class LanguageSpecificSpecificationFacetSpecificationDataCommentContent
		{

			private string idField;

			private string moderatedField;

			private string valueField;

			/// <remarks/>
			[System.Xml.Serialization.XmlAttributeAttribute()]
			public string id
			{
				get
				{
					return this.idField;
				}
				set
				{
					this.idField = value;
				}
			}
				
			/// <remarks/>
			[System.Xml.Serialization.XmlAttributeAttribute()]
			public string moderated
			{
				get
				{
					return this.moderatedField;
				}
				set
				{
					this.moderatedField = value;
				}
			}

			/// <remarks/>
			[System.Xml.Serialization.XmlTextAttribute()]
			public string Value
			{
				get
				{
					return this.valueField;
				}
				set
				{
					this.valueField = value;
				}
			}
		}

    }
}
